# MultiCurrency 0.1.0 developed by khanghoang
debug: true
# Set datasource of plugin. Available datasource are: yaml, mysql, sqlite
datasource: mysql
# MySQL configuration
mysql:
  tablePrefix: bank_
  host: localhost
  port: 3306
  database: mc
  username: mineviet
  password: 123456
  maxPoolSize: 10

currencies:
  tiengiay:
    name: "tiền giấy"
    symbol: "$"
    denominations: 
      1000: "1k"
      5000: "5k"
      10000: "10k"
      20000: "20k"
      50000: "50k"
      100000: "100k"
      200000: "200k"
      500000: "500k"
      1000000: "1 triệu"
    item: "PAPER"
    lores:
      - "aaaa"
      - "aaaa"
      - "aaaa"
    default: true
  xu:
    name: "xu"
    item: "SUNFLOWER"
    lores:
      - "aaaa"
      - "aaaa"
      - "aaaa"
    
    