# AdvancedOregen 1.0.1 developed by khanghoang
# Note: All the spawnrates should be less than 1.0 and the sum of them should be equals 1.0.
# The permission of each generator is starts with 'oregen.' and follow by its name (e.g 'oregen.vip').
# It must have one default generator. The default generator does not need any permission.
# Run plugin in debug mode
debug: true
# Here you can define your ore generator machine.
# The placeholders available are %oregen_label%, %oregen_name%, %oregen_permission%. 
# You need to install PlaceholderAPI to get it to work.
# The islandLevel attribute is the minimum insland level required to make the generator works.
generators:
  default:
    item: STONE
    label: Máy quặng khởi đầu
    symbol: '&7[F]' 
    blocks:
      STONE: 0.5
      IRON_BLOCK: 0.1
      LAPIS_BLOCK: 0.1
      COAL_ORE: 0.3
    islandLevel: 0
    rank: 1000
  vip:
    label: 'Gernerator 1'
    item: IRON_BLOCK
    symbol: '&f[&eS&f]' 
    blocks:
      STONE: 0.5
      IRON_BLOCK: 0.15
      LAPIS_BLOCK: 0.15
      COAL_ORE: 0.2
    islandLevel: 0
    rank: 1
# Here you can define worlds where the generator should not work
disabled-worlds:
- world_nether
